version: '3.8'
services:
  data:
    build:
      context: ./scraping
      dockerfile: Dockerfile
    container_name: scraping_data
    volumes:
      - .:/usr/src/app
      - data:/usr/src/app/data
  database:
    image: mysql
    container_name: scraping_database
    command: ["mysqld", "--datadir=pkg/api/db", "--port=${DB_PORT}"]
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOTPASS}
      - MYSQL_PORT=${DB_PORT}
      - MYSQL_DATABASE=${DBNAME}
    depends_on:
      - data
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: scraping_api
    env_file:
      - ./api/.env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/src/app
      - data:/usr/src/app/data
    depends_on:
      - database
  nodemailer:
    build: 
      context: ./mailer
      dockerfile: Dockerfile
    container_name: nodemailer
    volumes:
      - .:/usr/src/app/mailer
    env_file:
      - ./mailer/.env
    depends_on:
      - api
volumes:
  data: